---
title: "Figure4"
author: "Athena Golfinos-Owens"
date: "2025-01-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(dplyr)
library(tidyr)
library(readxl)
library(CellChat)
library(DescTools)
library(circlize)
library(openxlsx)
library(ComplexHeatmap)
library(ggplot2)
library(ggrepel)
library(grid)
library(future)
library(patchwork)
library(purrr)
library(readr)
library(stringr)
library(RColorBrewer)
library(ggraph)

# Set working directory to the script's location (RStudio only) 
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 

# Print the current working directory (optional, for verification) 
print(getwd())

color_clusters <- c("#DC050C", "#FB8072", "#1965B0", "#7BAFDE", "#882E72", "#B17BA6", "#FF7F00", "#FDB462", 
                    "#E7298A", "#E78AC3","#33A02C", "#B2DF8A", "#55A1B1", "#8DD3C7", "#A6761D", "#E6AB02", 
                    "#7570B3", "#BEAED4", "#666666", "#999999", "#AA8282", "#D4B7B7", "#8600BF", "#BA5CE3", 
                    "#808000","#AEAE5C", "#1E90FF", "#00BFFF", "#56FF0D", "#FFFF00")

## Object load-in
```{r}
# loading in necessary objects
```

#meta_chemokines <- readxl::read_excel('HNC_ICB_GolfinosOwens_etal_2025/CellChat/Barras_et_al_5CCI_metadata/Datafile_S7.xls', sheet = 'Chemokines')

```

```{r Preparation--Running CellChat}
out_dir <- "/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_cytokine"


# function to run CellChat
process_cellchat <- function(seu1, out, path_response, meta, tx_stage = NULL, features_keep = NULL) {
  
  require(CellChat)
  require(future)
  require(Seurat)
  
  # Filter seu1 by tx_stage if provided
  if (!is.null(tx_stage)) {
    seu1 <- seu1[, seu1$Stage == tx_stage]
  }
  
  # Filter seu1 by path_response
  seu <- seu1[, seu1$response_binary %in% path_response]
  
  # Set cell identities
  Idents(seu) <- meta
  
  # Create CellChat object
  cellchat <- createCellChat(seu)
  CellChatDB <- CellChatDB.human 
  CellChatDB.use <- CellChatDB # use the default CellChatDB
  cellchat@DB <- CellChatDB.use # set the used database in the object
  
  # Subset data
  if(is.null(features_keep)){
    cellchat <- subsetData(cellchat)
  }
  
  if(!is.null(features_keep)){
    cellchat <- subsetData(cellchat, features = features_keep)
  }
  
  # Parallel processing
  future::plan("multisession", workers = 4)
  
  # Identify over and under expressed genes/interactions
  cellchat <- identifyOverExpressedGenes(cellchat)
  cellchat <- identifyOverExpressedInteractions(cellchat)
  
  # Compute communication probability
  cellchat <- computeCommunProb(cellchat)
  
  # Filter out communication if very few cells in certain cell groups
  cellchat <- filterCommunication(cellchat, min.cells = 10)
  
  # Compute communication probability pathway
  cellchat <- computeCommunProbPathway(cellchat)
  
  # Aggregate network
  cellchat <- aggregateNet(cellchat)
  
  # Save objects
  if(!is.null(tx_stage)){
    save(cellchat, seu1, seu, CellChatDB, CellChatDB.use, file = paste(out, tx_stage, '_', path_response, '_grouped_cellchat_objects.rda', sep = ''))
  }
  
  if(is.null(tx_stage)){
    save(cellchat, seu1, seu, CellChatDB, CellChatDB.use, file = paste(out, path_response, '_grouped_cellchat_objects.rda', sep = ''))
  }
  
  # return cellchat object
  return(cellchat)
}




# pre-treatment responders
r_pre_cellchat <- process_cellchat(
  seu1 = luoma,
  out = out_dir,
  meta = 'consensus_clusters',
  tx_stage = "Pre-Tx",
  path_response = "Responder", 
  features_keep = as.character(c(meta_chemokines$receptor, meta_chemokines$ligand))
)

# pre-treatment non-responders
nr_pre_cellchat <- process_cellchat(
  seu1 = luoma,
  features_keep = c(meta_chemokines$ligand, meta_chemokines$receptor),
  meta = 'consensus_clusters',
  out = out_dir,
  tx_stage = "Pre-Tx",
  path_response = "Non-responder"
) 

# post-treatment responders
r_post_cellchat <- process_cellchat(
  seu1 = luoma,
  features = c(meta_chemokines$ligand, meta_chemokines$receptor),
  meta = 'consensus_clusters',
  out = out_dir,
  tx_stage = "Post-Tx",
  path_response = "Responder"
)

# post-treatment non-responders
nr_post_cellchat <- process_cellchat(
  seu1 = luoma,
  features = c(meta_chemokines$ligand, meta_chemokines$receptor),
  meta = 'consensus_clusters',
  out = out_dir,
  tx_stage = "Post-Tx",
  path_response = "Non-responder"
) 


# determine if there are subsets not present in all objects so we can remove them
all_levels <- unique(c(levels(r_post_cellchat@idents),
                       levels(nr_post_cellchat@idents),
                       levels(r_pre_cellchat@idents),
                       levels(nr_pre_cellchat@idents)))

cell_order1 <- levels(r_post_cellchat@idents) # 15
cell_order2 <- levels(nr_post_cellchat@idents) # 15
cell_order3 <- levels(r_pre_cellchat@idents) # 15
cell_order4 <- levels(nr_pre_cellchat@idents) # 15

cell_order <- intersect(cell_order1, cell_order2)
cell_order <- intersect(cell_order, cell_order3)
cell_order <- intersect(cell_order, cell_order4)

print(setdiff(all_levels, cell_order))
# character(0)


# establishing the same cell subset order before merging
r_pre_cellchat <- CellChat::updateClusterLabels(r_pre_cellchat, new.order = cell_order) %seed% TRUE
r_post_cellchat <- CellChat::updateClusterLabels(r_post_cellchat, new.order = cell_order) %seed% TRUE
nr_pre_cellchat <- CellChat::updateClusterLabels(nr_pre_cellchat, new.order = cell_order) %seed% TRUE
nr_post_cellchat <- CellChat::updateClusterLabels(nr_post_cellchat, new.order = cell_order) %seed% TRUE

# merging together the pre-tx (R and NR) and post-tx (R and NR)
pre.object.list <- list(NR = nr_pre_cellchat, R = r_pre_cellchat)
pre_cellchat <- mergeCellChat(pre.object.list, add.names = names(pre.object.list))

post.object.list <- list(NR = nr_post_cellchat, R = r_post_cellchat)
post_cellchat <- mergeCellChat(post.object.list, add.names = names(post.object.list))

save(pre_cellchat, post_cellchat, r_pre_cellchat, nr_pre_cellchat, r_post_cellchat, nr_post_cellchat, 
     file = paste(out_dir, 'all_cellchat_objs.rda', sep = ''))

```

```{r Fig 2a--Pre-Tx Chord}
load('Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_cytokine/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(pre_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(pre_cellchat@idents$joint), value = T)

nr_cellchat_chemokines <- subsetCommunication(nr_pre_cellchat, sources.use = send, targets.use = rec)
r_cellchat_chemokines <- subsetCommunication(r_pre_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_chemokines[nr_cellchat_chemokines$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_chemokines[r_cellchat_chemokines$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to myeloid to T only
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))
#select(sender, receiver, group_specificity, pathway, num_ints)

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))
#select(sender, receiver, group_specificity, pathway, num_ints)

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
#nr <- as.data.frame(table(nr_spec_ints$sr)) 
#nr <- nr %>% 
#  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
#  mutate(sender = paste(sender, '_NR', sep = '')) %>%
#  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
#  mutate(group_specificity = 'NR') %>%
#  mutate(pathway = 'Chemokine') %>%
#  relocate(Freq, .after = pathway) %>% 
#  rename(Freq = 'num_ints')

#r <- as.data.frame(table(r_spec_ints$sr))
#r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
#  mutate(sender = paste(sender, '_R', sep = '')) %>%
#  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
#  mutate(group_specificity = 'R') %>%
#  mutate(pathway = 'Chemokine') %>%
#  relocate(Freq, .after = pathway) %>%
#  rename(Freq = 'num_ints')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Chemokine') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

#chemokine_ints <- rbind(nr, r, shared)
chemokine_ints <- shared # there are no unique interactions per group, only shared

write.csv(chemokine_ints, file = 'chemokine_df.csv', row.names = F)



# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_complement/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(pre_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(pre_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_complement <- subsetCommunication(nr_pre_cellchat, sources.use = send, targets.use = rec)
r_cellchat_complement <- subsetCommunication(r_pre_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_complement[nr_cellchat_complement$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_complement[r_cellchat_complement$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) 
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # there are none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

Complement_ints <- rbind(r, nr, shared)

write.csv(Complement_ints, file = 'complement_df.csv', row.names = F)



# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_costim_coinhib/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(pre_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(pre_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_Costim_coinhib <- subsetCommunication(nr_pre_cellchat, sources.use = send, targets.use = rec)
r_cellchat_Costim_coinhib <- subsetCommunication(r_pre_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_Costim_coinhib[nr_cellchat_Costim_coinhib$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_Costim_coinhib[r_cellchat_Costim_coinhib$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) 
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # there are none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

Costim_coinhib_ints <- rbind(nr, r, shared)

write.csv(Costim_coinhib_ints, file = 'Costim_coinhib_df.csv', row.names = F)





# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_interleukin/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(pre_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(pre_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_Interleukin <- subsetCommunication(nr_pre_cellchat, sources.use = send, targets.use = rec)
r_cellchat_Interleukin <- subsetCommunication(r_pre_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_Interleukin[nr_cellchat_Interleukin$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_Interleukin[r_cellchat_Interleukin$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) # none
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Interleukin') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Interleukin') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Interleukin') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

Interleukin_ints <- rbind(nr, r, shared)

write.csv(Interleukin_ints, file = 'Interleukin_df.csv', row.names = F)

# loading all dataframes so we can combine them into one
chemokine_ints <- read.csv('chemokine_df.csv')
complement_ints <- read.csv('complement_df.csv')
Interleukin_ints <- read.csv('Interleukin_df.csv')
costim_coinhib_ints <- read.csv('Costim_coinhib_df.csv')

# combining all dataframes into one
all_ints <- rbind(chemokine_ints, complement_ints, Interleukin_ints, costim_coinhib_ints)
write.csv(all_ints, file = 'all_df.csv')



# load in data
mat <- read.csv('all_df.csv')
mat <- mat %>% select(-X)

nm = unique(unlist(dimnames(mat)))

Type_Cols <- c(Macrophage = "#548235", Monocyte = "#660066", DC = "#4472C4", CD4 = "#002060", 
               CD8 = 'darkred', Treg = 'darkorange')


sectors <- sort(unique(c(mat$sender, mat$receiver)))
group <- structure(sapply(strsplit(sectors,"_"), `[`, 1), names = sectors)
df.groups <- structure(sapply(strsplit(sectors,"_"), `[`, 1), names = sectors)
group

grid.col = structure(Type_Cols[match(sapply(strsplit(sectors,"_"), `[`, 1), 
                                     labels(Type_Cols))], names = sectors)

# Plotting the circos plot
pdf(file = 'PreTx_CCIPathwayCircos.pdf')
circos.clear()
circos.par(start.degree = 295)
chordDiagram(mat, group = group, grid.col = grid.col,
             col = ifelse(mat$pathway == 'Chemokine',"cyan3",
                          ifelse(mat$pathway == 'Complement',"darkseagreen",
                                 ifelse(mat$pathway == 'Costim_coinhib',"darksalmon",
                                        ifelse(mat$pathway == 'Interleukin',"darkorchid",
                                               "ERROR")))),
             annotationTrack = c("grid", "axis"),
             directional = 1,
             direction.type = c('diffHeight', 'arrows'),
             link.arr.type = "big.arrow",
             big.gap = 10,
             scale = T,
             preAllocateTracks = list(
               track.height = mm_h(4),
               track.margin = c(mm_h(4), 0)
             ))

for(si in get.all.sector.index()) {
  xlim = get.cell.meta.data("xlim", sector.index = si, track.index = 2)
  ylim = get.cell.meta.data("ylim", sector.index = si, track.index = 2)
  circos.text(mean(xlim), mean(ylim), sapply(strsplit(si,"_"), `[`, 2), sector.index = si, 
              col = "white", track.index = 2, cex = .7)
}

for (i in unique(df.groups)) {
  highlight.sector(grep(i, get.all.sector.index(), value = T), track.index = 1, 
                   col = Type_Cols[match(i, labels(Type_Cols))], text = i, 
                   text.vjust = -1, padding = c(-.2, 0, -.5, 0))
}

# adding a legend
lgd = Legend(labels = c('Chemokine', 'Complement', 'Costimulatory/Coinhibitory', 'Interleukin'), 
             title = "CCI pathway", legend_gp = gpar(fill = c('cyan3', 'darkseagreen', 'darksalmon', 'darkorchid')))
lgd_list_vertical = packLegend(lgd)
draw(lgd_list_vertical, x = unit(1, "cm"), y = unit(1, "cm"), just = c("left", 'bottom'))
dev.off()

save(df, mat, df.groups, grid.col, group, sectors, Type_Cols, 
     file = 'PreTx_5CCIs_Chord_all_workspace.rda')
```

```{r Fig 4a--Post-tx Circos plot}
# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_cytokine/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(post_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(post_cellchat@idents$joint), value = T)

nr_cellchat_chemokines <- subsetCommunication(nr_post_cellchat, sources.use = send, targets.use = rec)
r_cellchat_chemokines <- subsetCommunication(r_post_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_chemokines[nr_cellchat_chemokines$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_chemokines[r_cellchat_chemokines$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]

# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))
#select(sender, receiver, group_specificity, pathway, num_ints)

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))
#select(sender, receiver, group_specificity, pathway, num_ints)

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) 
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Chemokine') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')
r <- as.data.frame(table(r_spec_ints$sr))
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Chemokine') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')
shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Chemokine') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

chemokine_ints <- rbind(nr, r, shared)

write.csv(chemokine_ints, file = 'chemokine_df.csv', row.names = F)




# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_complement/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(post_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(post_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_complement <- subsetCommunication(nr_post_cellchat, sources.use = send, targets.use = rec)
r_cellchat_complement <- subsetCommunication(r_post_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_complement[nr_cellchat_complement$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_complement[r_cellchat_complement$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) 
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # there are none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Complement') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

Complement_ints <- rbind(r, nr, shared)

write.csv(Complement_ints, file = 'complement_df.csv', row.names = F)





# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_costim_coinhib/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(post_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(post_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_Costim_coinhib <- subsetCommunication(nr_post_cellchat, sources.use = send, targets.use = rec)
r_cellchat_Costim_coinhib <- subsetCommunication(r_post_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_Costim_coinhib[nr_cellchat_Costim_coinhib$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_Costim_coinhib[r_cellchat_Costim_coinhib$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) 
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # there are none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

shared <- as.data.frame(table(shared_ints$sr))
shared <- shared %>%
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
  mutate(group_specificity = 'Sh') %>%
  mutate(pathway = 'Costim_coinhib') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

Costim_coinhib_ints <- rbind(nr, r, shared)

write.csv(Costim_coinhib_ints, file = 'Costim_coinhib_df.csv', row.names = F)





# load in cellchat objects
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_interleukin/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(post_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(post_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_cellchat_Interleukin <- subsetCommunication(nr_post_cellchat, sources.use = send, targets.use = rec)
r_cellchat_Interleukin <- subsetCommunication(r_post_cellchat, sources.use = send, targets.use = rec)

# filter to those with probability > 0 and pval < 0.05
nr_ints <- nr_cellchat_Interleukin[nr_cellchat_Interleukin$prob > 0,]
nr_ints <- nr_ints[nr_ints$pval < 0.05,]
r_ints <- r_cellchat_Interleukin[r_cellchat_Interleukin$prob > 0,]

r_ints <- r_ints[r_ints$pval < 0.05,]
# filter to only myeloid senders
nr_ints_myeloid <- nr_ints[nr_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
r_ints_myeloid <- r_ints[r_ints$source %like any% c('%Mon%', '%Mac%', '%DC%'),]
# filter to only T cell receivers
nr_ints_myeloid <- nr_ints_myeloid[nr_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]
r_ints_myeloid <- r_ints_myeloid[r_ints_myeloid$target %like any% c('%CD4%', '%CD8%', '%Treg%'),]

# getting vectors of the unique sr lr pairs
nr_results_myeloid <- nr_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

r_results_myeloid <- r_ints_myeloid[,c('source', 'target', 'interaction_name')] %>% unique() %>%
  mutate(sender = case_when(
    source %like any% c('%Mon%') ~ "Monocyte",
    source %like any% c('%Mac%') ~ "Macrophage",
    source %like any% c('%DC%') ~ "DC")) %>%
  mutate(receiver = case_when(
    target %like any% c('%CD8%') ~ "CD8",
    target %like any% c('%CD4%') ~ "CD4",
    target %like any% c('%Treg%') ~ "Treg")) %>%
  mutate(sr = paste(sender, receiver, sep = '_')) %>%
  mutate(srlr = paste(sender, receiver, interaction_name, sep = '_'))

# getting interactions that are shared, r_specific, and nr_specific
shared <- intersect(r_results_myeloid$srlr, nr_results_myeloid$srlr)
nr_spec <- setdiff(nr_results_myeloid$srlr, r_results_myeloid$srlr)
r_spec <- setdiff(r_results_myeloid$srlr, nr_results_myeloid$srlr)

# getting the dataframe of  what's shared, vs. unique
nr_spec_ints <- nr_results_myeloid[nr_results_myeloid$srlr %in% nr_spec,]
r_spec_ints <- r_results_myeloid[r_results_myeloid$srlr %in% r_spec,]
shared_ints <- r_results_myeloid[r_results_myeloid$srlr %in% shared,] # doesn't matter which we pull from (r vs. nr) since they are shared

# getting a table of the interactions
nr <- as.data.frame(table(nr_spec_ints$sr)) # none
nr <- nr %>% 
  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_NR', sep = '')) %>%
  mutate(receiver = paste(receiver, '_NR', sep = '')) %>%
  mutate(group_specificity = 'NR') %>%
  mutate(pathway = 'Interleukin') %>%
  relocate(Freq, .after = pathway) %>% 
  rename(num_ints = 'Freq')

r <- as.data.frame(table(r_spec_ints$sr)) # none
r <- r %>% separate(Var1, c('sender', 'receiver'), sep = '_') %>%
  mutate(sender = paste(sender, '_R', sep = '')) %>%
  mutate(receiver = paste(receiver, '_R', sep = '')) %>%
  mutate(group_specificity = 'R') %>%
  mutate(pathway = 'Interleukin') %>%
  relocate(Freq, .after = pathway) %>%
  rename(num_ints = 'Freq')

#shared <- as.data.frame(table(shared_ints$sr))
#shared <- shared %>%
#  separate(Var1, c('sender', 'receiver'), sep = '_') %>%
#  mutate(sender = paste(sender, '_Sh', sep = '')) %>%
#  mutate(receiver = paste(receiver, '_Sh', sep = '')) %>%
#  mutate(group_specificity = 'Sh') %>%
#  mutate(pathway = 'Interleukin') %>%
#  relocate(Freq, .after = pathway) %>%
#  rename(num_ints = 'Freq')

#Interleukin_ints <- rbind(nr, r, shared)
Interleukin_ints <- rbind(nr, r)

write.csv(Interleukin_ints, file = 'Interleukin_df.csv', row.names = F)

# loading all dataframes so we can combine them into one
chemokine_ints <- read.csv('chemokine_df.csv')
complement_ints <- read.csv('complement_df.csv')
Interleukin_ints <- read.csv('Interleukin_df.csv')
costim_coinhib_ints <- read.csv('Costim_coinhib_df.csv')

# combining all dataframes into one
all_ints <- rbind(chemokine_ints, complement_ints, Interleukin_ints, costim_coinhib_ints)
write.csv(all_ints, file = 'all_df.csv')

# load in data
mat <- read.csv('all_df.csv')
mat <- mat %>% select(-X)

nm = unique(unlist(dimnames(mat)))

Type_Cols <- c(Macrophage = "#548235", Monocyte = "#660066", DC = "#4472C4", CD4 = "#002060", 
               CD8 = 'darkred', Treg = 'darkorange')


sectors <- sort(unique(c(mat$sender, mat$receiver)))
group <- structure(sapply(strsplit(sectors,"_"), `[`, 1), names = sectors)
df.groups <- structure(sapply(strsplit(sectors,"_"), `[`, 1), names = sectors)
group

grid.col = structure(Type_Cols[match(sapply(strsplit(sectors,"_"), `[`, 1), 
                                     labels(Type_Cols))], names = sectors)

# Plotting the circos plot
pdf(file = 'PostTx_CCIPathwayCircos.pdf')
circos.clear()
circos.par(start.degree = 295)
chordDiagram(mat, group = group, grid.col = grid.col,
             col = ifelse(mat$pathway == 'Chemokine',"cyan3",
                          ifelse(mat$pathway == 'Complement',"darkseagreen",
                                 ifelse(mat$pathway == 'Costim_coinhib',"darksalmon",
                                        ifelse(mat$pathway == 'Interleukin',"darkorchid",
                                               "ERROR")))),
             annotationTrack = c("grid", "axis"),
             directional = 1,
             direction.type = c('diffHeight', 'arrows'),
             link.arr.type = "big.arrow",
             big.gap = 10,
             scale = T,
             preAllocateTracks = list(
               track.height = mm_h(4),
               track.margin = c(mm_h(4), 0)
             ))

for(si in get.all.sector.index()) {
  xlim = get.cell.meta.data("xlim", sector.index = si, track.index = 2)
  ylim = get.cell.meta.data("ylim", sector.index = si, track.index = 2)
  circos.text(mean(xlim), mean(ylim), sapply(strsplit(si,"_"), `[`, 2), sector.index = si, 
              col = "white", track.index = 2, cex = .7)
}

for (i in unique(df.groups)) {
  highlight.sector(grep(i, get.all.sector.index(), value = T), track.index = 1, 
                   col = Type_Cols[match(i, labels(Type_Cols))], text = i, 
                   text.vjust = -1, padding = c(-.2, 0, -.5, 0))
}

# adding a legend
lgd = Legend(labels = c('Chemokine', 'Complement', 'Costimulatory/Coinhibitory', 'Interleukin'), 
             title = "CCI pathway", legend_gp = gpar(fill = c('cyan3', 'darkseagreen', 'darksalmon', 'darkorchid')))
lgd_list_vertical = packLegend(lgd)
draw(lgd_list_vertical, x = unit(1, "cm"), y = unit(1, "cm"), just = c("left", 'bottom'))
dev.off()




save(df, mat, df.groups, grid.col, group, sectors, Type_Cols, 
     file = 'PostTx_5CCIs_Chord_all_workspace.rda')
```

```{r Fig 4b--rank plot (pre-treatment and post-treatment)}
load('/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/Luoma_cytokine/all_cellchat_objs.rda')

# keeping track of the subsets that we do/don't want to include
send <- grep('Mac|Mon|DC', levels(pre_cellchat@idents$joint), value = T)
rec <- grep('CD4|CD8|Treg|Tcells', levels(pre_cellchat@idents$joint), value = T)

# get objects that contain group name and interaction probability
nr_pre <- subsetCommunication(nr_pre_cellchat, sources.use = send, targets.use = rec) %>% 
  select(c('source', 'target', 'ligand', 'receptor', 'prob')) %>%
  unite(SRLR, c('source', 'target', 'ligand', 'receptor'), sep = '->') %>%
  plyr::rename(c('prob' = 'NR_pre_prob'))
nr_post <- subsetCommunication(nr_post_cellchat, sources.use = send, targets.use = rec) %>%
  select(c('source', 'target', 'ligand', 'receptor', 'prob')) %>%
  unite(SRLR, c('source', 'target', 'ligand', 'receptor'), sep = '->') %>%
  plyr::rename(c('prob' = 'NR_post_prob'))
r_pre <- subsetCommunication(r_pre_cellchat, sources.use = send, targets.use = rec) %>%
  select(c('source', 'target', 'ligand', 'receptor', 'prob')) %>%
  unite(SRLR, c('source', 'target', 'ligand', 'receptor'), sep = '->') %>%
  plyr::rename(c('prob' = 'R_pre_prob'))
r_post <- subsetCommunication(r_post_cellchat, sources.use = send, targets.use = rec) %>%
  select(c('source', 'target', 'ligand', 'receptor', 'prob')) %>%
  unite(SRLR, c('source', 'target', 'ligand', 'receptor'), sep = '->') %>%
  plyr::rename(c('prob' = 'R_post_prob'))
#nr_post <- nr_post[-grep('SPP1', nr_post$SRLR),]
r_post <- r_post[-grep('SPP1', r_post$SRLR),]

# merge down to two objects and calculate log2FC and rank
pre <- merge(r_pre, nr_pre, by = 'SRLR') %>%
  mutate(log2FC = log2(R_pre_prob/NR_pre_prob)) %>%
  arrange(desc(log2FC)) %>%
  mutate(rank = row_number()) %>%
  separate(SRLR, c('sender', 'receiver', 'ligand', 'receptor'), sep = '->')
post <- merge(r_post, nr_post, by = 'SRLR')  %>%
  mutate(log2FC = log2(R_post_prob/NR_post_prob)) %>%
  arrange(desc(log2FC)) %>%
  mutate(rank = row_number()) %>%
  separate(SRLR, c('sender', 'receiver', 'ligand', 'receptor'), sep = '->')


# Create a color column
pre$color_group <- case_when(
  pre$log2FC > 1 ~ "R_enriched",
  pre$log2FC < -1 ~ "NR_enriched",
  TRUE ~ "Unchanged"
)

post$color_group <- case_when(
  post$log2FC > 1 ~ "R_enriched",
  post$log2FC < -1 ~ "NR_enriched",
  TRUE ~ "Unchanged"
)


# Define colors for senders and receivers
sender_colors <- c("mregDC_LAMP3" = "#DC050C", "Mac_CXCL9" = "#FB8072", 'Blood-like_CD14_Mono' = "#1965B0",
                   'Mac_IL1B' = "#7BAFDE", 'cDC2_CD33' = "#882E72", 'Mac_IL1Bint' = "#B17BA6", #'CD16_Mono' = "#FF7F00", 
                   'cDC2_CD1C' = "#FDB462", 'cDC1_CLEC9A' = "#E7298A", 'Mono_TIL' = "#E78AC3")
receiver_colors <- c("ITGAE_CD8" = "#33A02C", "CXCL13_Tcells" = "#B2DF8A", 'Tregs' = "#55A1B1", 'GZMK_CD8' = "#8DD3C7", 
                     'IL7R_CD4' = "#7570B3", 'NR4A2_CD8' = "#BEAED4")

# Create the base plot with all points--post-treatment

create_label_grob <- function(ligand, receptor, sender_color, receiver_color) {
  label <- paste(ligand, receptor, sep = " | ")
  text_width <- convertWidth(stringWidth(label), "npc", valueOnly = TRUE)
  min_width <- 35 # Set a minimum width for the rectangles
  adjusted_width <- max(text_width, min_width)
  grobTree(
    rectGrob(gp = gpar(fill = receiver_color, col = NA), width = unit(adjusted_width / 2, "npc"), height = unit(1, "lines"), just = "left"),
    rectGrob(gp = gpar(fill = sender_color, col = NA), x = unit(0.5, "npc"), width = unit(adjusted_width / 2, "npc"), height = unit(1, "lines"), just = "right"),
    textGrob(label, x = 0.5, y = 0.5, just = "center", gp = gpar(col = "white"))
  )
}
p <- ggplot(pre, aes(x = rank, y = log2FC)) +
  geom_point(data = pre, aes(color = sender, fill = receiver), shape = 21) +  # Plot all points with color and fill
  theme_classic() +
  labs(title = "Chemokine: Pre-ICB CCI rank",
       x = "CCI rank", y = "log2FC(R/NR CCI count)") +
  scale_x_continuous(limits = c(-10, 110)) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 28),
        legend.position = "none", axis.text=element_text(size=12),
        axis.title=element_text(size=18,face="bold"))
# Add custom annotations for log2FC > 1 or log2FC < -1
significant_points <- subset(pre, log2FC > 2.5 | log2FC < - 1)
for (i in 1:nrow(significant_points)) {
  label_grob <- create_label_grob(
    significant_points$ligand[i],
    significant_points$receptor[i],
    sender_colors[significant_points$sender[i]],
    receiver_colors[significant_points$receiver[i]]
  )
  p <- p + annotation_custom(
    grob = label_grob,
    xmin = significant_points$rank[i] - 0.5,
    xmax = significant_points$rank[i] + 0.5,
    ymin = significant_points$log2FC[i] - 0.5,
    ymax = significant_points$log2FC[i] + 0.5
  )
}
# Add horizontal lines at y = 1 and y = -1
p <- p + geom_hline(yintercept = c(-1, 1), linetype = "dashed", color = "grey")
# Add legends for sender and receiver colors with correct order and appearance
p <- p + scale_color_manual(name = "Sender", 
                            values = sender_colors, 
                            breaks = names(sender_colors),
                            guide = guide_legend(order = 1, 
                                                 override.aes = list(shape = 22, 
                                                                     size = 5, 
                                                                     fill = sender_colors, 
                                                                     color = NA))) +
  scale_fill_manual(name = "Receiver", 
                    values = receiver_colors, 
                    breaks = names(receiver_colors),
                    guide = guide_legend(order = 2, 
                                         override.aes = list(shape = 22, 
                                                             size = 5, 
                                                             color = NA)))
# Adjust legend appearance and layout
p <- p + theme(
  legend.key = element_rect(colour = NA),
  legend.key.size = unit(1.2, "cm"),  # Increased key size
  legend.text = element_text(size = 14),  # Increased text size
  legend.title = element_text(size = 16, face = "bold"),  # Increased title size
  legend.position = "none",
  legend.box = "vertical",
  legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
  legend.box.margin = margin(0, 0, 0, 0),
  legend.spacing.x = unit(0, 'cm'),  # Increased spacing
  legend.spacing.y = unit(0, 'cm'),  # Increased spacing
  plot.margin = margin(t = 5, r = 5, b = 25, l = 5, unit = "pt")  # Increased bottom margin
)
# Adjust the guide for sender legend to use two rows, keep receiver legend as one row
p <- p + guides(
  color = guide_legend(nrow = 2, byrow = TRUE, order = 1, 
                       override.aes = list(shape = 22, 
                                           size = 6,  # Increased size
                                           fill = sender_colors, 
                                           color = NA)),
  fill = guide_legend(nrow = 1, byrow = TRUE, order = 2,
                      override.aes = list(shape = 22, 
                                          size = 6,  # Increased size
                                          color = NA))
)
# Save the plot with increased height
pdf('PreTx_srlr_rankplot.pdf', width = 6.5, height = 5)  # Increased height
print(p)
dev.off()












sender_colors <- c("mregDC_LAMP3" = "#DC050C", "Mac_CXCL9" = "#FB8072", 'Blood-like_CD14_Mono' = "#1965B0",
                   'Mac_IL1B' = "#7BAFDE", 'cDC2_CD33' = "#882E72", 'Mac_IL1Bint' = "#B17BA6", 'CD16_Mono' = "#FF7F00", 
                   'cDC2_CD1C' = "#FDB462", 'cDC1_CLEC9A' = "#E7298A", 'Mono_TIL' = "#E78AC3", 'DC_pDC' = "#8600BF")
receiver_colors <- c("ITGAE_CD8" = "#33A02C", "CXCL13_Tcells" = "#B2DF8A", 'Tregs' = "#55A1B1", 'GZMK_CD8' = "#8DD3C7", 
                     'IL7R_CD4' = "#7570B3", 'NR4A2_CD8' = "#BEAED4")

create_label_grob <- function(ligand, receptor, sender_color, receiver_color) {
  label <- paste(ligand, receptor, sep = " | ")
  text_width <- convertWidth(stringWidth(label), "npc", valueOnly = TRUE)
  min_width <- 35 # Set a minimum width for the rectangles
  adjusted_width <- max(text_width, min_width)
  grobTree(
    rectGrob(gp = gpar(fill = receiver_color, col = NA), width = unit(adjusted_width / 2, "npc"), height = unit(1, "lines"), just = "left"),
    rectGrob(gp = gpar(fill = sender_color, col = NA), x = unit(0.5, "npc"), width = unit(adjusted_width / 2, "npc"), height = unit(1, "lines"), just = "right"),
    textGrob(label, x = 0.5, y = 0.5, just = "center", gp = gpar(col = "white"))
  )
}
p <- ggplot(post, aes(x = rank, y = log2FC)) +
  geom_point(data = post, aes(color = sender, fill = receiver), shape = 21) +  # Plot all points with color and fill
  theme_classic() +
  labs(title = "Chemokine: Post-ICB CCI rank",
       x = "CCI rank", y = "log2FC(R/NR CCI count)") +
  scale_x_continuous(limits = c(-10, 120)) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 28),
        legend.position = "none", axis.text=element_text(size=12),
        axis.title=element_text(size=18,face="bold"))
# Add custom annotations for log2FC > 1 or log2FC < -1
significant_points <- subset(post, log2FC > 1.5 | log2FC < - 1)
for (i in 1:nrow(significant_points)) {
  label_grob <- create_label_grob(
    significant_points$ligand[i],
    significant_points$receptor[i],
    sender_colors[significant_points$sender[i]],
    receiver_colors[significant_points$receiver[i]]
  )
  p <- p + annotation_custom(
    grob = label_grob,
    xmin = significant_points$rank[i] - 0.5,
    xmax = significant_points$rank[i] + 0.5,
    ymin = significant_points$log2FC[i] - 0.5,
    ymax = significant_points$log2FC[i] + 0.5
  )
}
# Add horizontal lines at y = 1 and y = -1
p <- p + geom_hline(yintercept = c(-1, 1), linetype = "dashed", color = "grey")
# Add legends for sender and receiver colors with correct order and appearance
p <- p + scale_color_manual(name = "Sender", 
                            values = sender_colors, 
                            breaks = names(sender_colors),
                            guide = guide_legend(order = 1, 
                                                 override.aes = list(shape = 22, 
                                                                     size = 5, 
                                                                     fill = sender_colors, 
                                                                     color = NA))) +
  scale_fill_manual(name = "Receiver", 
                    values = receiver_colors, 
                    breaks = names(receiver_colors),
                    guide = guide_legend(order = 2, 
                                         override.aes = list(shape = 22, 
                                                             size = 5, 
                                                             color = NA)))
# Adjust legend appearance and layout
p <- p + theme(
  legend.key = element_rect(colour = NA),
  legend.key.size = unit(1.2, "cm"),  # Increased key size
  legend.text = element_text(size = 14),  # Increased text size
  legend.title = element_text(size = 16, face = "bold"),  # Increased title size
  legend.position = "none",
  legend.box = "vertical",
  legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
  legend.box.margin = margin(0, 0, 0, 0),
  legend.spacing.x = unit(0, 'cm'),  # Increased spacing
  legend.spacing.y = unit(0, 'cm'),  # Increased spacing
  plot.margin = margin(t = 5, r = 5, b = 25, l = 5, unit = "pt")  # Increased bottom margin
)
# Adjust the guide for sender legend to use two rows, keep receiver legend as one row
p <- p + guides(
  color = guide_legend(nrow = 2, byrow = TRUE, order = 1, 
                       override.aes = list(shape = 22, 
                                           size = 6,  # Increased size
                                           fill = sender_colors, 
                                           color = NA)),
  fill = guide_legend(nrow = 1, byrow = TRUE, order = 2,
                      override.aes = list(shape = 22, 
                                          size = 6,  # Increased size
                                          color = NA))
)
# Save the plot with increased height
pdf('PostTx_srlr_rankplot.pdf', width = 6.5, height = 5)  # Increased height
print(p)
dev.off()
```

```{r Fig 4c--Running per Neighborhood CellChat for heatmap}
CosMX_RNA_merged$k10_NhCoord20_anno[CosMX_RNA_merged$k10_NhCoord20_anno == "Myeloid_K17+_Tumor_Mixed"] <- 'Myeloid_K17_Tumor_Mixed'

# Get unique entries from k10_NhCoord20_anno
unique_entries <- unique(CosMX_RNA_merged$k10_NhCoord20_anno)

# Define the analysis function
run_analysis <- function(entry) {
  cosmx_rna_nh <- CosMX_RNA_merged[,grep(entry, CosMX_RNA_merged$k10_NhCoord20_anno)]
  
  data.input1 = Seurat::GetAssayData(cosmx_rna_nh[,cosmx_rna_nh$Response == 'R'], slot = "data", assay = "SCT")
  data.input2 = Seurat::GetAssayData(cosmx_rna_nh[,cosmx_rna_nh$Response == 'NR'], slot = "data", assay = "SCT")
  
  genes.common <- intersect(rownames(data.input1), rownames(data.input2))
  colnames(data.input1) <- paste0("R_", colnames(data.input1))
  colnames(data.input2) <- paste0("NR_", colnames(data.input2))
  
  meta1 = data.frame(labels = cosmx_rna_nh[,cosmx_rna_nh$Response == 'R']$annot_cluster2, samples = cosmx_rna_nh[,cosmx_rna_nh$Response == 'R']$tma_fov_id)
  meta2 = data.frame(labels = cosmx_rna_nh[,cosmx_rna_nh$Response == 'NR']$annot_cluster2, samples = cosmx_rna_nh[,cosmx_rna_nh$Response == 'NR']$tma_fov_id)
  
  rownames(meta1) <- colnames(data.input1)
  rownames(meta2) <- colnames(data.input2)
  meta1$labels <- factor(meta1$labels, levels = unique(meta1$labels))
  meta1$samples <- factor(meta1$samples, levels = unique(meta1$samples))
  meta2$labels <- factor(meta2$labels, levels = unique(meta2$labels))
  meta2$samples <- factor(meta2$samples, levels = unique(meta2$samples))
  
  r_cellchat <- createCellChat(object = data.input1, meta = meta1, group.by = "labels", datatype = "RNA")
  nr_cellchat <- createCellChat(object = data.input2, meta = meta2, group.by = "labels", datatype = "RNA")
  
  CellChatDB <- CellChatDB.human 
  CellChatDB.use <- subsetDB(CellChatDB)
  
  r_cellchat@DB <- CellChatDB.use
  nr_cellchat@DB <- CellChatDB.use
  
  r_cellchat <- subsetData(r_cellchat)
  future::plan("multisession", workers = 4) 
  r_cellchat <- identifyOverExpressedGenes(r_cellchat)
  r_cellchat <- identifyOverExpressedInteractions(r_cellchat)
  r_cellchat <- computeCommunProb(r_cellchat, type = "truncatedMean", trim = 0.1, distance.use = F)
  r_cellchat <- filterCommunication(r_cellchat, min.cells = 10)
  r_cellchat <- computeCommunProbPathway(r_cellchat)
  r_cellchat <- aggregateNet(r_cellchat)
  
  nr_cellchat <- subsetData(nr_cellchat)
  future::plan("multisession", workers = 4) 
  nr_cellchat <- identifyOverExpressedGenes(nr_cellchat)
  nr_cellchat <- identifyOverExpressedInteractions(nr_cellchat)
  nr_cellchat <- computeCommunProb(nr_cellchat, type = "truncatedMean", trim = 0.1, distance.use = F)
  nr_cellchat <- filterCommunication(nr_cellchat, min.cells = 10)
  nr_cellchat <- computeCommunProbPathway(nr_cellchat)
  nr_cellchat <- aggregateNet(nr_cellchat)
  
  all_levels <- unique(c(levels(r_cellchat@idents), levels(nr_cellchat@idents)))
  cell_order1 <- levels(r_cellchat@idents) 
  cell_order2 <- levels(nr_cellchat@idents)
  cell_order <- intersect(cell_order1, cell_order2)
  
  r_cellchat <- CellChat::updateClusterLabels(r_cellchat, new.order = cell_order) %seed% TRUE
  nr_cellchat <- CellChat::updateClusterLabels(nr_cellchat, new.order = cell_order) %seed% TRUE
  
  pathways.show <- c("CXCL") 
  
  color_clusters <- c("#DC050C", "#FB8072", "#1965B0", "#7BAFDE", "#882E72", "#B17BA6", "#FF7F00", "#FDB462",
                      "#E7298A", "#E78AC3","#33A02C", "#B2DF8A", "#55A1B1", "#8DD3C7", "#A6761D", "#E6AB02", 
                      "#7570B3", "#BEAED4", "#666666", "#999999", "#AA8282", "#D4B7B7", "#8600BF", "#BA5CE3", 
                      "#808000","#AEAE5C", "#1E90FF", "#00BFFF", "#56FF0D", "#FFFF00")
  
  p1 <- netVisual_aggregate(nr_cellchat, signaling = pathways.show, layout = "circle", 
                            sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), 
                            targets.use = grep('Tcells|CD8|CD4|Treg', meta1$labels, value = T), remove.isolate = T)
  pdf(paste0(entry, '_NR_circos.pdf'), width = 6, height = 6)
  print(p1)
  dev.off() 
  
  p2 <- netVisual_aggregate(r_cellchat, signaling = pathways.show, layout = "circle", 
                            sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), 
                            targets.use = grep('Tcells|CD8|CD4|Treg', meta1$labels, value = T), remove.isolate = T)
  pdf(paste0(entry, '_R_circos.pdf'), width = 6, height = 6)
  print(p2)
  dev.off()
  
  pdf(paste0(entry, '_myeloid_to_tcell_chord_diagram_NR_R.pdf'), pointsize = 12, height = 6, width = 9)
  print(cowplot::plot_grid(p2, p1, ncol = 2))
  dev.off()
  
  r <- subsetCommunication(r_cellchat, sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), targets.use = grep('Tcells|CD8|CD4|Treg', meta1$labels, value = T))
  nr <- subsetCommunication(nr_cellchat, sources.use = grep('Mon|Mac|DC', meta2$labels, value = T), targets.use = grep('Tcells|CD8|CD4|Treg', meta2$labels, value = T))
  
  r_cxcl <- subsetCommunication(r_cellchat, sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), targets.use = grep('Tcells|CD8|CD4|Treg', meta1$labels, value = T), signaling = 'CXCL')
  nr_cxcl <- subsetCommunication(nr_cellchat, sources.use = grep('Mon|Mac|DC', meta2$labels, value = T), targets.use = grep('Tcells|CD8|CD4|Treg', meta2$labels, value = T), signaling = 'CXCL')
  
  save(r_cellchat, nr_cellchat, CellChatDB, CellChatDB.use, cosmx_rna_nh, data.input1, data.input2, meta1, meta2,
       file = paste0(entry, '_workspace.rda'))
  
  cellchat <- mergeCellChat(list(r_cellchat, nr_cellchat), add.names = c('Responder', 'Non-Responder'))
  
  gg1 <- rankNet(cellchat, mode = "comparison", measure = "weight", sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), 
                 targets.use = grep('Treg|CD4|CD8', meta1$labels, value = T), stacked = T, do.stat = TRUE, return.data = T)
  gg2 <- rankNet(cellchat, mode = "comparison", measure = "weight", sources.use = grep('Mon|Mac|DC', meta1$labels, value = T), 
                 targets.use = grep('Treg|CD4|CD8', meta1$labels, value = T), stacked = F, do.stat = TRUE, return.data = T)
  
  stacked_df <- gg1$signaling.contribution
  unstacked_df <- gg2$signaling.contribution
  
  # Save additional results if needed
  save(stacked_df, unstacked_df, file = paste0(entry, '_additional_results.rda'))
}

# Loop through unique entries and run the analysis
for (entry in unique_entries) {
  tryCatch({
    cat("Processing entry:", entry, "\n")
    run_analysis(entry)
    cat("Completed processing for entry:", entry, "\n\n")
  }, error = function(e) {
    cat("Error processing entry:", entry, "\n")
    cat("Error message:", conditionMessage(e), "\n\n")
  })
}

```

```{r Fig 4c--only myeloid senders!preparing pathway by probability dataframe for heatmap and plotting}
# Define file paths
files <- c(
  '/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/NoSpatial_1NH_all_patients_per_response_immune_NHs_k10_NhCoord20_annoTumor_Immune_Mixed_workspace.rda',
  '/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/NoSpatial_1NH_all_patients_per_response_immune_NHs_k10_NhCoord20_anno/Myeloid_K17_Tumor_Mixed_workspace.rda',
  '/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/NoSpatial_1NH_all_patients_per_response_immune_NHs_k10_NhCoord20_anno/Macrophage_High_workspace.rda',
  '/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/NoSpatial_1NH_all_patients_per_response_immune_NHs_k10_NhCoord20_anno/DC_T_iCAF_Tumor_Mixed_workspace.rda',
  '/Golfinos_Owen_et_al_HNSCC_ICI/SeuratObjects_dataFrames/NoSpatial_1NH_all_patients_per_response_immune_NHs_k10_NhCoord20_anno/CAF_Immune_Mixed_workspace.rda'
)

# Function to load workspace and extract CellChat objects
load_cellchat_objects <- function(file_path) {
  load(file_path)
  
  # Check if objects exist
  if (!exists("nr_cellchat") || !exists("r_cellchat")) {
    stop(paste("Missing nr_cellchat or r_cellchat in", file_path))
  }
  
  list(
    nr = nr_cellchat,
    r = r_cellchat
  )
}

# Function to extract the name
extract_name <- function(file_path) {
  file_name <- basename(file_path) # Gets filename
  name <- gsub("_workspace\\.rda$", "", file_name)  # Removes suffix
  return(name)
}

# Apply the function to all files and store in a list
cellchat_list <- map(files, load_cellchat_objects)

# Extract the names for the list
names(cellchat_list) <- map_chr(files, extract_name)

# Print the structure of the resulting list
str(cellchat_list, max.level = 2)

# Initialize list to store merged CellChat objects
merged_cellchat_list <- list()

# Merge CellChat objects for each neighborhood
for (neighborhood in names(cellchat_list)) {
  # Merge nr and r CellChat objects
  nr <- cellchat_list[[neighborhood]]$nr
  r <- cellchat_list[[neighborhood]]$r
  
  # Perform the merging
  merged_cellchat <- tryCatch({
    mergeCellChat(list(R = r, NR = nr), add.names = c("R", "NR"))
  }, error = function(e) {
    message(sprintf("Error merging %s: %s", neighborhood, e$message))
    return(NULL)
  })
  
  # Check the results
  if (!is.null(merged_cellchat)) {
    merged_cellchat_list[[neighborhood]] <- merged_cellchat
  }
}

# Filter out NULL entries (failed merges)
merged_cellchat_list <- merged_cellchat_list[!sapply(merged_cellchat_list, is.null)]

# Get all unique pathways from merged objects
all_pathways <- unique(merged_cellchat_list[[1]]@netP$R$pathways)

# Initialize list to store results
results_list <- list()

# Loop through merged CellChat objects and pathways
for (neighborhood in names(merged_cellchat_list)) {
  merged_cellchat_obj <- merged_cellchat_list[[neighborhood]]
  
  # Initialize list for this neighborhood's results
  neighborhood_results <- list()
  
  # Loop through pathways
  for (pathway in all_pathways) {
    tryCatch({
      # Run netVisual_bubble and extract data
      plot_data <- netVisual_bubble(
        merged_cellchat_obj,
        signaling = pathway,
        sources.use = c('Macrophages', 'Monocytes', 'DCs'),
        targets.use = c('TcellsCD8+', 'Tcells_CD4+', 'Tregs'),
        remove.isolate = FALSE,
        return.data = TRUE,
        comparison = c(1, 2)
      )
      
      # Add pathway and neighborhood information
      result_df <- plot_data$communication %>%
        mutate(
          pathway = pathway,
          neighborhood = neighborhood
        )
      
      # Store results
      neighborhood_results[[pathway]] <- result_df
    }, error = function(e) {
      message(sprintf("Error processing pathway %s in %s: %s",
                      pathway, neighborhood, e$message))
    })
  }
  
  # Combine results for this neighborhood
  if (length(neighborhood_results) > 0) {
    combined_results <- bind_rows(neighborhood_results)
    results_list[[neighborhood]] <- combined_results
  }
}

# Combine all results into a single dataframe
final_results <- bind_rows(results_list)

# Print the structure of the final results
str(final_results)

final_results <- final_results %>%
  mutate(
    neighborhood = case_when(
      neighborhood == "Tumor_Immune_Mixed" ~ 'Tumor_Immune_Tcell_High',
      neighborhood == "Macrophage_High" ~ "Immune_Macrophage_High",
      neighborhood == "DC_T_iCAF_Tumor_Mixed" ~ "ap_iCAF_Immune_Mixed",
      neighborhood == "CAF_Immune_Mixed" ~ "myCAF_Immune_Mixed",
      TRUE ~ as.character(neighborhood)
    )
  )


# Save the results
write.csv(final_results, "cellchat_netVisual_bubble_merged_results.csv", row.names = FALSE)






# Optionally, save the results
combined_df <- read.csv("cellchat_netVisual_bubble_merged_results.csv")

combined_df <- combined_df[grep('CXCL|CCL|^IL', combined_df$pathway), ]

combined_df <- combined_df %>%
  mutate(
    neighborhood = case_when(
      neighborhood == "Tumor_Immune_Mixed" ~ 'Tumor_Immune_Tcell_High',
      neighborhood == "Macrophage_High" ~ "Immune_Macrophage_High",
      neighborhood == "DC_T_iCAF_Tumor_Mixed" ~ "ap_iCAF_Immune_Mixed",
      neighborhood == "CAF_Immune_Mixed" ~ "myCAF_Immune_Mixed",
      TRUE ~ as.character(neighborhood)
    )
  )





combined_df <- combined_df %>% 
  select('source.target', 'interaction_name', 'neighborhood', 'prob', 'pathway')
combined_df$id <- paste(combined_df$source.target, combined_df$neighborhood)
combined_df$id2 <- paste(combined_df$interaction_name, combined_df$pathway)

combined_df$prob[is.na(combined_df$prob)] <- 0

combined_df <- combined_df %>%
  group_by(neighborhood) %>%
  mutate(
    #prob.original_rescaled = (prob.original - min(prob.original)) / (max(prob.original) - min(prob.original)),
    prob_rescaled = (prob - min(prob)) / (max(prob) - min(prob))
  ) %>%
  ungroup()


anno_df_col <- combined_df 
anno_df_row <- combined_df


anno_df_col$Response <- str_extract(anno_df_col$source.target, "\\(([^)]+)\\)")
anno_df_col$Response <- str_remove_all(anno_df_col$Response, "[()]")
anno_df_col <- anno_df_col %>%
  select('Response', 'id', 'neighborhood')
anno_df_col <- unique(anno_df_col)
anno_df_col <- anno_df_col[!is.na(anno_df_col$Response),]

anno_df_col <- anno_df_col %>%
  separate("id", into = c("sender", "temp"), sep = "->", remove = FALSE) %>%
  separate("temp", into = c("receiver", "response"), sep = "\\(", remove = TRUE)


combined_df_wide <- combined_df %>% 
  select('id', 'id2', 'prob_rescaled')
combined_df_wide <- unique(combined_df_wide)
combined_df_wide <- tidyr::pivot_wider(combined_df_wide, names_from = id, values_from = prob_rescaled)

combined_df_wide <- as.data.frame(combined_df_wide[!is.na(combined_df_wide$id2),])
combined_df_wide[is.na(combined_df_wide)] <- 0
combined_df_wide <- combined_df_wide[grep('NA ', combined_df_wide$id, invert = T),]
rownames(combined_df_wide) <- combined_df_wide$id2
combined_df_wide$id2 <- NULL

# Define a vector of distinct colors for your neighborhoods
neighborhood_colors <- c(
  "Tumor_Immune_Tcell_High" = "#E41A1C",
  "Myeloid_K17_Tumor_Mixed" = "#377EB8",
  "Immune_Macrophage_High" = "#4DAF4A",
  "ap_iCAF_Immune_Mixed" = "#984EA3",
  "myCAF_Immune_Mixed"  = "#FF7F00"
)

response_colors <- c(
  'R' = '#FF8A80',
  'NR' = '#2196F3'
)

sender_colors <- c(
  "Monocytes " = 'green',
  "Macrophages " = 'green4',
  "DCs " = 'navy'
)

receiver_colors <- c(
  ' TcellsCD8+ ' = 'yellow',
  ' Tcells_CD4+ ' = 'skyblue',
  ' Tregs ' = 'orange'
)

# Create the column annotation
col_anno <- ComplexHeatmap::HeatmapAnnotation(
  Neighborhood = anno_df_col$neighborhood,
  Response = anno_df_col$Response,
  Sender = anno_df_col$sender,
  Receiver = anno_df_col$receiver,
  col = list(Neighborhood = neighborhood_colors, 
             Response = response_colors,
             Sender = sender_colors,
             Receiver = receiver_colors),
  show_legend = TRUE
)


# remove NAs
combined_df_wide <- combined_df_wide[,!colnames(combined_df_wide) %like% c('%NA %')]
short_colnames <- sub("\\s*\\(.*", "", colnames(combined_df_wide))
# Create the matrix with shortened column names
mat <- as.matrix(combined_df_wide)
#colnames(mat) <- short_colnames


anno_df_row <- data.frame(rownames(combined_df_wide))
anno_df_row <- anno_df_row %>% separate(`rownames.combined_df_wide.`, c("int", "pathway"), sep = " ", remove = F) %>%
  select(`rownames.combined_df_wide.`, pathway) %>%
  tibble::column_to_rownames("rownames.combined_df_wide.")

# Create the column annotation
row_ha <- ComplexHeatmap::rowAnnotation(
  Pathway = anno_df_row$pathway,
  #col = list(Neighborhood = neighborhood_colors),
  show_legend = TRUE
)


pdf('noMHC_COLLAGEN_fromDP_nh_contribution.pdf', height = 20, width = 18)
# Now use this matrix in your Heatmap function
ComplexHeatmap::draw(ComplexHeatmap::Heatmap(mat,
             name = "Probability",
             #column_title = "Merged Column",
             row_title = "Interaction Name",
             right_annotation = row_ha,
             top_annotation = col_anno,
             show_row_names = TRUE,
             show_column_names = TRUE,
             column_names_rot = 90,
             clustering_distance_columns = "euclidean",
             clustering_method_columns = "complete",
             clustering_distance_rows = "euclidean",
             clustering_method_rows = "complete", 
             column_names_max_height = unit(15, 'cm')))
dev.off()
```

```{r Fig 4d-DotPlot of ligand (myeloid) and receptor (T cells) in tumor/immune/Tcell high NHs}
CosMX_RNA_merged <- CosMX_RNA_merged %>%
  Seurat::AddMetaData(
    metadata = case_when(
      CosMX_RNA_merged$k10_NhCoord20_anno == "Tumor_Immune_Mixed" ~ 'Tumor_Immune_Tcell_High',
      CosMX_RNA_merged$k10_NhCoord20_anno == "Macrophage_High" ~ "Immune_Macrophage_High",
      CosMX_RNA_merged$k10_NhCoord20_anno == "DC_T_iCAF_Tumor_Mixed" ~ "ap_iCAF_Immune_Mixed",
      CosMX_RNA_merged$k10_NhCoord20_anno == "CAF_Immune_Mixed" ~ "myCAF_Immune_Mixed",
      TRUE ~ as.character(CosMX_RNA_merged$k10_NhCoord20_anno)
    ), col.name = "k10_NhCoord20_anno_new"
  )

 unique(CosMX_RNA_merged$k10_NhCoord20_anno_new)
#[1] "Bcell_Plasma"             "Endothelial"              "Tumor_Immune_Tcell_High" 
#[4] "ap_iCAF_Immune_Mixed"     "Immune_Macrophage_High"   "myCAF_Immune_Mixed"      
#[7] "CAFs"                     "Tumor_High"               "Myeloid_K17+_Tumor_Mixed"
 
immune_macrophage_high <- CosMX_RNA_merged[,CosMX_RNA_merged$k10_NhCoord20_anno_new == "Immune_Macrophage_High"]

p1 <- DotPlot(immune_macrophage_high[,grep('Mon|Mac|DC', immune_macrophage_high$annot_cluster2)], features = c('CXCL9', 'CXCL10', 'CXCL16', 'CCL5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

p2 <- DotPlot(immune_macrophage_high[,grep('CD4|CD8|Treg', immune_macrophage_high$annot_cluster2)], features = c('CXCR3', 'CXCR6', 'CCR5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

pdf('immune_macrophage_high_NH_CXCL_CCL_dotplot_by_response.pdf', width = 14, height = 4)
cowplot::plot_grid(p1, p2)
dev.off()
 
 
 
 
myeloid_k17_tumor_mixed <- CosMX_RNA_merged[,CosMX_RNA_merged$k10_NhCoord20_anno_new == "Myeloid_K17+_Tumor_Mixed"]

p1 <- DotPlot(myeloid_k17_tumor_mixed[,grep('Mon|Mac|DC', myeloid_k17_tumor_mixed$annot_cluster2)], features = c('CXCL9', 'CXCL10', 'CXCL16', 'CCL5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

p2 <- DotPlot(myeloid_k17_tumor_mixed[,grep('CD4|CD8|Treg', myeloid_k17_tumor_mixed$annot_cluster2)], features = c('CXCR3', 'CXCR6', 'CCR5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

pdf('myeloid_k17_tumor_mixed_NH_CXCL_CCL_dotplot_by_response.pdf', width = 13, height = 4)
cowplot::plot_grid(p1, p2)
dev.off()



p1 <- DotPlot(myeloid_k17_tumor_mixed[,grep('Mon|Mac|DC', myeloid_k17_tumor_mixed$annot_cluster2)], features = c('IL1B', 'CCL4', 'CCL3', 'CCL13'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

p2 <- DotPlot(myeloid_k17_tumor_mixed[,grep('CD4|CD8|Treg', myeloid_k17_tumor_mixed$annot_cluster2)], features = c('IL1R1', 'IL1R2', 'CCR5', 'CCR1'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

pdf('myeloid_k17_tumor_mixed_NH_IL_CCL_dotplot_by_response.pdf', width = 12, height = 4)
cowplot::plot_grid(p1, p2)
dev.off()
 
 
 

tumor_immune_tcell_high <- CosMX_RNA_merged[,CosMX_RNA_merged$k10_NhCoord20_anno_new == "Tumor_Immune_Tcell_High"]

p1 <- DotPlot(tumor_immune_tcell_high[,grep('Mon|Mac|DC', tumor_immune_tcell_high$annot_cluster2)], features = c('CXCL9', 'CXCL10', 'CXCL16', 'CCL5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

p2 <- DotPlot(tumor_immune_tcell_high[,grep('CD4|CD8|Treg', tumor_immune_tcell_high$annot_cluster2)], features = c('CXCR3', 'CXCR6', 'CCR5'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

pdf('tumor_immune_tcell_high_NH_CXCL_CCL_dotplot_by_response.pdf', width = 14, height = 4)
cowplot::plot_grid(p1, p2)
dev.off()


p1 <- DotPlot(tumor_immune_tcell_high[,grep('Mon|Mac|DC', tumor_immune_tcell_high$annot_cluster2)], features = c('IL16', 'IL11', 'CCL19', 'CCL21'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

p2 <- DotPlot(tumor_immune_tcell_high[,grep('CD4|CD8|Treg', tumor_immune_tcell_high$annot_cluster2)], features = c('CCR7', 'CD4', 'IL11RA'), col.min = 0, cols = 'RdBu', split.by = 'Response', group.by = 'annot_cluster2')

pdf('tumor_immune_tcell_high_NH_IL_CCL_dotplot_by_response.pdf', width = 12, height = 4)
cowplot::plot_grid(p1, p2)
dev.off()
```

